services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${SQL_USER}", "-p$${SQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enschnei/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enschnei/data/wordpress
      o: bind
